apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: hello-go
spec:
  serviceName: hello-go
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: gcr.io/gcp-demo-200100/hello-go
        ports:
        - containerPort: 80
          name: primary
        volumeMounts:
        - name: hello-go-pvc
          mountPath: /etc
  volumeClaimTemplates:
  - metadata:
      name: hello-go-pvc
      annotations:
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
