apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: gcr.io/<your project ID>/hello-go
  googleCloudBuild:
    projectId: <your project ID>
deploy:
  kubectl:
    manifests:
    - hello-go-ingress.yaml
    - hello-go-ss.yaml
    - hello-go-svc.yaml
