apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/cloud-tools-201201/hello-go
    workspace: .
    docker: {}
  local: {}
  kaniko:
    gcsBucket: gs://hello-go-contexts
    pullSecret: /Users/tariqislam/opt/sa/kaniko-sa.json
deploy:
  kubectl:
    manifests:
      - hello-go*
