apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/cloud-tools-201201/hello-go
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
      - hello-go*
