apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: gcr.io/gcp-demo-200100/hello-go
  googleCloudBuild:
    projectId: gcp-demo-200100
deploy:
  kubectl:
    manifests:
    - hello-go-ingress.yaml
    - hello-go-ss.yaml
    - hello-go-svc.yaml
